routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('product', ProductController::class);

Route::get('/', [WebController::class, 'index']);
Route::post('/userRegister', [WebController::class, 'userRegister']);
Route::post('/addToCart', [WebController::class, 'addToCart']);
Route::get('/cart', [WebController::class, 'cart'])->middleware('auth');
Route::post('/checkout', [WebController::class, 'checkout'])->middleware('auth');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'tbl_product';

    protected $fillable = [
        'img',
        'nama_produk',
        'harga',
        'stock',
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use Auth;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            if (Auth::user()->akses == 1) {
                return abort(401);
            }

            return $next($request);
        });
    }

    public function index()
    {
        $product = Product::get();

        return view('cms.product.index')->with(['no' => 1, 'product' => $product]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cms.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_produk' => 'required|unique:tbl_product',
            'img' => 'mimes:jpeg,png,jpg|max:5000',
        ]);

        $img = $request->file('img');
        $destinationPath = public_path('storage/img/product');
        if(!is_dir($destinationPath)){
            mkdir($destinationPath, 0755, true);
        }
        $imgName = time().'.'.$img->getClientOriginalExtension();
        $img->move($destinationPath, $imgName); 

        Product::create([ 
            'img' => $imgName,
            'nama_produk' => $request->nama_produk,
            'harga' => str_replace(".", "", $request->harga),
            'stock' => $request->stock,
        ]);

        return redirect()->route('product.index')->with('alert-success', "Data saved successfully!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);

        return view('cms.product.show')->with(['product' => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        return view('cms.product.edit')->with(['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_produk' => 'required|unique:tbl_product,nama_produk,'.$id,
            'img' => 'mimes:jpeg,png,jpg|max:5000',
        ]);

        $form = [ 
            'nama_produk' => $request->nama_produk,
            'harga' => str_replace(".", "", $request->harga),
            'stock' => $request->stock,
        ];

        if ($request->img) {
            $img = $request->file('img');
            $destinationPath = public_path('storage/img/product');
            if(!is_dir($destinationPath)){
                mkdir($destinationPath, 0755, true);
            }
            $imgName = time().'.'.$img->getClientOriginalExtension();
            $img->move($destinationPath, $imgName); 
            $form['img'] = $imgName;
        }

        Product::where('id', $id)->update($form);

        return redirect()->route('product.index')->with('alert-success', "Data updated successfully!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);

        return redirect()->route('product.index')->with('alert-success', "Data deleted successfully!");
    }
}

resources/views/cms/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Product Create
                </div>
                <div class="card-body">
                    @if($errors->any())
                        {!! implode('', $errors->all('<div class="alert alert-danger" role="alert">:message</div>')) !!}
                    @endif
                    <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                      <div class="form-group">
                        <label for="#">Image</label><br>
                        <img src="" alt="" style="width: 100px;height: 100px;margin-bottom: 10px;display: none;">
                        <input type='file' name="img" id="img" onchange="readURL(this);" class="form-control" accept="image/*" required />
                      </div>
                      <div class="form-group">
                        <label for="#">Product Name</label>
                        <input type='text' name="nama_produk" class="form-control" placeholder="-" required />
                      </div>
                      <div class="form-group">
                        <label for="#">Stock</label>
                        <input type='number' name="stock" class="form-control" placeholder="-" required />
                      </div>
                      <div class="form-group">
                        <label for="#">Price</label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <div class="input-group-text">Rp</div>
                            </div>
                            <input type='text' name="harga" id="harga" class="form-control" placeholder="-" required />
                        </div>
                      </div>
                      <hr>
                      <div class="float-right">
                        <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                        <a href="{{ route('product.index') }}" class="btn btn-sm btn-danger">Cancel</a>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.13.4/jquery.mask.min.js"></script>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(input).parent().children("img").show()
                        .attr('src', e.target.result)
                        .width(100)
                        .height(100);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#harga').mask("#.##0", {reverse: true});
    </script>
@endsection

resources/views/cms/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Product Edit
                </div>

                <div class="card-body">
                    @if($errors->any())
                        {!! implode('', $errors->all('<div class="alert alert-danger" role="alert">:message</div>')) !!}
                    @endif
                    <form action="{{ route('product.update',$product->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                      <div class="form-group">
                        <label for="#">Image</label><br>
                        <img src="{{ url('/') }}/storage/img/product/{{ $product->img }}" alt="" style="width: 100px;height: 100px;margin-bottom: 10px;display:">
                        <input type='file' name="img" id="img" onchange="readURL(this);" class="form-control" accept="image/*"/>
                      </div>
                      <div class="form-group">
                        <label for="#">Product Name</label>
                        <input type='text' name="nama_produk" class="form-control" value="{{ $product->nama_produk }}" required />
                      </div>
                      <div class="form-group">
                        <label for="#">Stock</label>
                        <input type='number' name="stock" class="form-control" value="{{ $product->stock }}" required />
                      </div>
                      <div class="form-group">
                        <label for="#">Price</label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <div class="input-group-text">Rp</div>
                            </div>
                            <input type='text' name="harga" id="harga" class="form-control" value="{{ $product->harga }}" required />
                        </div>
                      </div>
                      <hr>
                      <div class="float-right">
                        <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                        <a href="{{ route('product.index') }}" class="btn btn-sm btn-danger">Cancel</a>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.13.4/jquery.mask.min.js"></script>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(input).parent().children("img").show()
                        .attr('src', e.target.result)
                        .width(100)
                        .height(100);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#harga').mask("#.##0", {reverse: true});
    </script>
@endsection

resources/views/cms/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Product List
                    <a href="{{ route('product.create') }}" class="btn btn-sm btn-success float-right">+ add product</a>
                </div>

                <div class="card-body">
                    @if(session()->has('alert-success'))
                        <div class="alert alert-success">
                            {{ session()->get('alert-success') }}
                        </div>
                    @endif
                    <table class="table table-striped table-bordered" style="width:100%" id="product">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Image</th>
                                <th>Product Name</th>
                                <th>Stock</th>
                                <th>Price</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                           @foreach($product as $v)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>
                                    <a href="{{ url('/') }}/storage/img/product/{{ $v->img }}" target="_blank"><img src="{{ url('/') }}/storage/img/product/{{ $v->img }}" width="80" height="80"></a>
                                </td>
                                <td>{{ $v->nama_produk }}</td>
                                <td>{{ $v->stock }}</td>
                                <td>Rp{{ number_format($v->harga, 0, ".", ".") }}</td>
                                <td>
                                    <form action="{{ route('product.destroy',$v->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ route('product.show',$v->id) }}" class="btn btn-sm btn-success">View</a>
                                        <a href="{{ route('product.edit',$v->id) }}" class="btn btn-sm btn-primary">Edit</a>
                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Apakah anda yakin ingin menghapus produk tersebut!')">Delete</button>
                                    </form>
                                </td>
                            </tr>
                           @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script type="text/javascript">
        $(document).ready(function() {
            $('#product').DataTable();
        });
    </script>
@endsection

resources/views/cms/product/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Product Detail
                </div>

                <div class="card-body">
                    <form>
                        <img src="{{ url('/') }}/storage/img/product/{{ $product->img }}" alt="" style="width: 100px;height: 100px;margin-bottom: 10px;display:">
                      <div class="form-group">
                        <label for="#">Product Name</label>
                        <input type='text' name="nama_produk" class="form-control" value="{{ $product->nama_produk }}" disabled />
                      </div>
                      <div class="form-group">
                        <label for="#">Stock</label>
                        <input type='number' name="stock" class="form-control" value="{{ $product->stock }}" disabled />
                      </div>
                      <div class="form-group">
                        <label for="#">Price</label>
                        <input type='text' name="harga" class="form-control" value="Rp{{ number_format($product->harga, 0, ".", ".") }}" disabled />
                      </div>
                      <hr>
                      <div class="float-right">
                        <a href="{{ route('product.index') }}" class="btn btn-sm btn-success">Back</a>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.13.4/jquery.mask.min.js"></script>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(input).parent().children("img").show()
                        .attr('src', e.target.result)
                        .width(100)
                        .height(100);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#harga').mask("#.##0", {reverse: true});
    </script>
@endsection